saito_fb/config/routes.rb
Rails.application.routes.draw do
  resources :facebooks do
    collection do
    post :confirm
    end
  end
  resources :users
  root 'users#new' 
  resources :sessions
end

saito_fb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

saito_fb/app/models/facebook.rb
class Facebook < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title,:content,:image, presence: true
  belongs_to:user
end

saito_fb/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, uniqueness: true, length: {maximum: 30},
  format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: {maximum: 8}
  before_validation { email.downcase!}
  has_secure_password
  has_many:facebooks
end

saito_fb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

saito_fb/app/controllers/facebooks_controller.rb
class FacebooksController < ApplicationController
  before_action :set_facebook,only:[:edit,:update,:destroy]
  def index
    @facebooks = Facebook.all
  end
  def new
    if params[:back]
      @facebook = Facebook.new(fb_params)
    else
      @facebook = Facebook.new
    end
    @facebook.user_id = current_user.id
  end
  def create
    @facebook = Facebook.new(fb_params)
    @facebook.user_id = current_user.id
    if @facebook.save
      redirect_to new_facebook_path
    else
      render "new"
    end
  end
  def edit
  end
  def update
    if @facebook.update(fb_params)
      redirect_to facebooks_path
    else
      render "edit"
    end
  end
  def destroy
    @facebook.destroy
    redirect_to facebooks_path
  end
  def confirm
    @facebook = Facebook.new(fb_params)
    @facebook.user_id = current_user.id
    render "new" if @facebook.invalid?
  end

  private

  def fb_params
    params.require(:facebook).permit(:title,:content,:image,:image_cache,:back)
  end
  def set_facebook
    @facebook = Facebook.find(params[:id])
  end
end

saito_fb/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id #パスワードが一致していたら、セッションにユーザーIDを代入
      redirect_to user_path(user.id)#詳細画面にリダイレクトして表示
    else
      flash.now[:danger]="ログインに失敗しました"
      render "new"
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

saito_fb/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
    render "new"
    end
  end
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

saito_fb/app/helpers/application_helper.rb
module ApplicationHelper
end

saito_fb/app/helpers/facebooks_helper.rb
module FacebooksHelper
  def choose_new_or_edit
    if action_name === "new"|| action_name === "confirm"
      confirm_facebooks_path
    elsif action_name === "edit"
      facebooks_path
    end
  end
end

saito_fb/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
  @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

saito_fb/app/helpers/users_helper.rb
module UsersHelper
end

saito_fb/app/views/facebooks/confirm.html.erb
<h1>以下の内容で送信します</h1>
<%= form_with(model: @facebook, local: true ,url: facebooks_path) do |form| %>
　　<div class="fb_content">
  　　<%= form.hidden_field :title %>
  　　<%= form.hidden_field :content %>
  　　<%= form.hidden_field image_tag(@facebook.image.url) if @facebook.image && @facebook.image.url %>
  　　<%= form.hidden_field :image_cache %>
　　</div>
  　<p>Title:<%= @facebook.title %></p>
  　<p>Content:<%= @facebook.content %></p>
  　<p>image:<%= image_tag @facebook.image.url ,size:"100x100" %></p>
  　<%= form.submit "登録する"%>
<% end %>

<%= form_with(model: @facebook, local: true, url: new_facebook_path,method: "get") do |form| %>
　　<div class="fb_content">
  　　<%= form.hidden_field :title %>
  　　<%= form.hidden_field :content %>
  　　<%= form.hidden_field image_tag(@facebook.image.url) if @facebook.image && @facebook.image.url %>
  　　<%= form.hidden_field :image_cache %>
　　</div>
<%= form.submit "戻る", name: 'back'%>
<% end %>

saito_fb/app/views/facebooks/edit.html.erb
<h1>ブログを編集する</h1>

<%= form_with(model: @facebook, local: true) do |form| %>
  <% if @facebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= @facebook.errors.count %>件のエラーがあります。</h2>
    　  <ul>
      　  <% @facebook.errors.full_messages.each do |msg| %>
        　  <li><%= msg %></li>
      　　<% end %>
    　　</ul>
　  </div>
  <% end %>
  <div class="fb_content">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="fb_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="fb_content">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= image_tag(@facebook.image.url) if @facebook.image && @facebook.image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "投稿する" %>
    </div>
<% end %>

saito_fb/app/views/facebooks/index.html.erb
<h1>投稿一覧</h1>
<% @facebooks.each do |facebook| %>
  <div class="list-group">
    <a class="list-group-item">
      <h4 class="list-group-item-text">投稿者:<%= facebook.user.name %></h4>
		  <h4 class="list-group-item-heading">タイトル:<%= facebook.title %></h4>
		  <p class="list-group-item-text">内容:<%= facebook.content %></p>
      <p class="list-group-item-text">画像:<%= image_tag facebook.image.url ,size:"100x100" %></p>
    　<%= link_to "ブログを編集する", edit_facebook_path(facebook.id) %>
    　<%= link_to "ブログを削除する", facebook_path(facebook.id), method: :delete, data: {confirm: "本当に削除していいですか？"}  %>
	  </a>
  </div>
<% end %>
<%= link_to "新規投稿画面に戻る", new_facebook_path %>

saito_fb/app/views/facebooks/new.html.erb
<h1>投稿を作成</h1>
<h2><%=@facebook.user.name %></h2>
<%= form_with(model: @facebook, local: true, url: choose_new_or_edit) do |form| %>
  <% if @facebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= @facebook.errors.count %>件のエラーがあります。</h2>
      　　<ul>
        　　<% @facebook.errors.full_messages.each do |msg| %>
          　　<li><%= msg %></li>
        　　<% end %>
      　　</ul>
  　</div>
  <% end %>
  <div class="fb_content">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="fb_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="fb_content">
    <%= form.label :image %>
    <%= image_tag(@facebook.image.url) if @facebook.image && @facebook.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
    <%= form.submit "投稿" %>
    <%= link_to "ブログ一覧",facebooks_path %>
<% end %>

saito_fb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <title>SaitoFb</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <nav class="navbar navbar-default">
    	  <div class="container-fluid">
    		  <div class="navbar-header">
    			  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarFacebook">
    				  <span class="sr-only">Toggle navigation</span>
    				  <span class="icon-bar"></span>
    				  <span class="icon-bar"></span>
    				  <span class="icon-bar"></span>
    			  </button>
    		    <a class="navbar-brand">Facebook</a>
    		  </div>
          <div class="collapse navbar-collapse" id="navbarFacebook">
            <ul class="nav navbar-nav">
              <% if logged_in? %>
        	      <li><%= link_to "新規投稿", new_facebook_path %></li>
        	      <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "アカウント作成", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
            </ul>
		      </div>
        </div>
      </nav>
    </header>
    <div class="center">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

saito_fb/app/views/users/new.html.erb
<h1>アカウント作成</h1>
<%= form_with(model: @user,local:true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      　　<ul>
        　　<% @user.errors.full_messages.each do |msg| %>
          　　<li><%= msg %></li>
        　　<% end %>
      　　</ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit  %>
<% end %>

saito_fb/app/views/users/show.html.erb
<h1>アカウント情報</h1>
<p>名前:<%= @user.name %></p>
<p>メールアドレス:<%= @user.email %></p>